"""Step 6b: inline the exported JSON into the dashboard template.

Kept as a separate step so the page and its data are versioned independently:
the template is edited by hand, the data is regenerated by the pipeline, and
neither has to be pasted into the other.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dustcast.config import ARTIFACTS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "dashboard" / "_template.html"
OUT = ROOT / "dashboard" / "dustcast.html"


def main() -> int:
    data = json.loads((ARTIFACTS / "step6_dashboard.json").read_text())
    html = TEMPLATE.read_text()
    marker = "/*__DATA__*/null"
    if marker not in html:
        raise SystemExit(f"template is missing the {marker} placeholder")
    OUT.write_text(html.replace(marker, json.dumps(data, separators=(",", ":"))))
    print(f"wrote {OUT}  ({OUT.stat().st_size / 1024:.0f} kB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
